server {
    listen 80;
    server_name lintas.geocitra.com;
    server_tokens off;

    # Endpoint untuk perpanjangan Certbot otomatis
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect semua traffic HTTP ke HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name lintas.geocitra.com;
    server_tokens off;

    # Path Sertifikat (Certbot)
    ssl_certificate /etc/letsencrypt/live/lintas.geocitra.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lintas.geocitra.com/privkey.pem;

    # SSL Optimasi
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Optimasi Upload & Timeout (Penting untuk upload data aset/gambar)
    client_max_body_size 100M;
    proxy_read_timeout 300s;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;

    location / {
        # Tembak ke container nginx milik lintas (sesuai container_name baru)
	proxy_pass http://172.18.0.18:80;        
        
	proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Tambahan agar Laravel bisa mendeteksi HTTPS dengan benar
        proxy_set_header X-Forwarded-Port 443;
        
        # Buffer settings untuk kestabilan koneksi
        proxy_buffering off;
        proxy_request_buffering off;
    }

    # Logging khusus untuk Lintas agar mudah debug
    error_log  /var/log/nginx/lintas_error.log;
    access_log /var/log/nginx/lintas_access.log;
}
