# --- BLOK HTTP ---
server {
    listen 80;
    server_name arsip.geocitra.com;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Paksa semua pengunjung masuk ke HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# --- BLOK HTTPS ---
server {
    listen 443 ssl;
    server_name arsip.geocitra.com;
    server_tokens off;

    # Sertifikat SSL
    ssl_certificate /etc/letsencrypt/live/arsip.geocitra.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/arsip.geocitra.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Limit ukuran file (penting buat upload dokumen besar)
    client_max_body_size 50M;

    # [1] ROUTING FRONTEND
    location / {
        proxy_pass http://arsip-fe:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # [2] ROUTING BACKEND
    location /api {
        proxy_pass http://arsip-be:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # [3] ROUTING FOTO/FILE
    location /uploads {
        proxy_pass http://arsip-be:5000/uploads;
        proxy_set_header Host $host;
    }
}
