server {
    listen 80;
    server_name geomeet.geocitra.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name geomeet.geocitra.com;

    ssl_certificate /etc/letsencrypt/live/geomeet.geocitra.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/geomeet.geocitra.com/privkey.pem;

    #include /etc/nginx/conf.d/ssl.conf;

    location / {
        proxy_pass http://202.10.45.157:8282;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
        tcp_nodelay on;

        proxy_read_timeout 900s;
        proxy_send_timeout 900s;
    }

    location /xmpp-websocket {
        proxy_pass http://202.10.45.157:8282/xmpp-websocket;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
    }

    location /colibri-ws {
        proxy_pass http://202.10.45.157:8282/colibri-ws;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
    }
}
