server {
    listen 80;
    server_name litera.geocitra.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name litera.geocitra.com;

    # Konfigurasi Sertifikat Litera
    ssl_certificate /etc/letsencrypt/live/litera.geocitra.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/litera.geocitra.com/privkey.pem;
    
    # Protokol SSL standar (Jangan pakai include ssl.conf disini)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # --- TAMBAHKAN BAGIAN INI ---
    location /socket.io/ {
        proxy_pass http://litera-be:4000; # Arahkan ke container backend
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # --- TAMBAHAN PENTING UNTUK WEBSOCKET ---
        
        # 1. Pastikan koneksi WebSocket tidak di-cache oleh Nginx
        proxy_cache_bypass $http_upgrade;
        
        # 2. Cegah Nginx memutus koneksi jika tidak ada aktivitas (defaultnya Nginx memutus setelah 60 detik)
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        
        # 3. Matikan buffering agar pesan real-time (seperti chat/sinyal video) langsung dikirim tanpa ditahan
        proxy_buffering off;
    }
    # ----------------------------

    # [BEST PRACTICE] Routing langsung ke nama container Frontend
    location / {
        proxy_pass http://litera-fe:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    # --- BAGIAN BARU UNTUK PDF ---
    location /uploads/ {
        proxy_pass http://litera-be:4000/uploads/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header Access-Control-Allow-Origin *;
    }

    # [BEST PRACTICE] Routing langsung ke nama container Backend
    location /api {
        proxy_pass http://litera-be:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
