server {
    listen 80;
    server_name pamjaya.keuanganku.id;
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl;
    server_name pamjaya.keuanganku.id;

    ssl_certificate /etc/letsencrypt/live/pamjaya.keuanganku.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pamjaya.keuanganku.id/privkey.pem;

    # [1] FRONTEND (Container pamjaya-fe port 4002)
    location / {
        proxy_pass http://pamjaya-fe:4002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # [2] BACKEND (Container pamjaya-be port 4003)
    location /api {
        proxy_pass http://pamjaya-be:4003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
