# --- BLOK HTTP (Port 80) ---
server {
    listen 80;
    server_name rekas.geocitra.com;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect otomatis HTTP ke HTTPS (Aktifkan ini!)
    location / {
        return 301 https://$host$request_uri;
    }
}

# --- BLOK HTTPS (Port 443) ---
server {
    listen 443 ssl;
    server_name rekas.geocitra.com;
    server_tokens off;

    # Pastikan path ini benar (sesuai output certbot tadi)
    ssl_certificate /etc/letsencrypt/live/rekas.geocitra.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rekas.geocitra.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # [1] ROUTING BACKEND (API)
    location /api {
        # Arahkan ke container backend (port 3000)
        proxy_pass http://rekas-be:3000;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # [2] ROUTING FRONTEND
    location / {
        # Arahkan ke container frontend (port 80)
        proxy_pass http://rekas-fe:80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
